### ISSUE TITLE
Store E2E Password

### ISSUE THREAD

**Issue by qoheniac** [flathub/chat.rocket.RocketChat#71] opened 2021-11-04 15:16 UTC
Not sure if the problem is upstream but the client does not store my E2E password and thus I have to type it every time I launch the app.

**Comment by geekgonecrazy** [comment] 2023-09-25 18:49
I'd open a bug upstream in the main repo and close this one.  
As this isn't really related to the desktop app at all.  Definitely not the flatpak but the web app

**Comment by andrevmatos** [comment] 2023-09-25 22:54
Could not reproduce locally; either an upstream client issue, or some issue between server and client, but nothing related to flatpak. Please, reopen if you have any hint that this is specific to this downstream package.

**Closed by andrevmatos** 2023-09-25 22:54 UTC
